#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the checkMagazine function below.
def checkMagazine(magazine, note):

    dictionaryMagazine = {}
    dictionaryNote = {}
    ret = 0

    for word in magazine:
        if word not in dictionaryMagazine:
            dictionaryMagazine[word] = 1
        else:
            dictionaryMagazine[word] += 1
    
    for word in note:
        if word not in dictionaryNote:
            dictionaryNote[word] = 1
        else:
            dictionaryNote[word] += 1

    for word in note:
        if word in dictionaryNote and word not in dictionaryMagazine:
            ret = 1
        else:
            if dictionaryMagazine[word] < dictionaryNote[word]:
                ret = 1
    
    if ret == 0:
        print("Yes")
    if ret == 1:
        print("No")


if __name__ == '__main__':
    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    magazine = input().rstrip().split()

    note = input().rstrip().split()

    checkMagazine(magazine, note)
